version: '3.8'

services:

  prometheus:
    container_name: prometheus
    env_file:
      - './.env'    
    image: prom/prometheus:v2.40.6
    volumes:
      - '${PROMETHUS_CONFIG_FILE_PATH_LOCAL}:${PROMETHUS_CONFIG_FILE_PATH}'
    command: "--config.file=${PROMETHUS_CONFIG_FILE_PATH}/prometheus.yaml"
    ports:
      - ${PROMETHUS_PORT}:${PROMETHUS_PORT}

  loki:
    container_name: loki
    env_file:
      - './.env'
    image: 'grafana/loki:2.7.1'
    command: '-config.file=${LOKI_CONFIG_PATH}/${LOKI_CONFIG_FILE}'
    ports:
      - '${LOKI_PORT}:${LOKI_PORT}'

  tempo:
    container_name: tempo
    env_file:
      - './.env'
    image: 'grafana/tempo:1.5.0'
    volumes:
      - '${TEMPO_CONFIG_PATH_LOCAL}:${TEMPO_CONFIG_PATH}'
    command:
      - '-config.file=${TEMPO_CONFIG_PATH}/${TEMPO_CONFIG_FILE}'
      - '-config.expand-env=true'
    ports:
      - '${TEMPO_PORT}:${TEMPO_PORT}'

  grafana:
    container_name: grafana
    env_file:
      - './.env'
    image: 'grafana/grafana:9.3.1'
    volumes:
      - '${GRAFANA_CONFIG_PATH_LOCAL}:${GRAFANA_CONFIG_PATH}'
      - '${GRAFANA_DATASOURCES_PATH_LOCAL}:${GRAFANA_DATASOURCES_PATH}'
      - '${GRAFANA_DASHBOARDS_PROVISIONING_PATH_LOCAL}:${GRAFANA_DASHBOARDS_PROVISIONING_PATH}'
      - '${GRAFANA_DASHBOARDS_PATH_LOCAL}:${GRAFANA_DASHBOARDS_PATH}'
      - '${GRAFANA_PLUGINS_PATH_LOCAL}:${GRAFANA_PLUGINS_PATH}'
      - '${GRAFANA_PLUGINS_PROVISIONING_PATH_LOCAL}:${GRAFANA_PLUGINS_PROVISIONING_PATH}'
    entrypoint:
      - '${GRAFANA_HOME_PATH}/bin/grafana-server'
      - '--homepath=${GRAFANA_HOME_PATH}'
      - '--config=${GRAFANA_CONFIG_PATH}/${GRAFANA_CONFIG_FILE}'
    ports:
      - '${GRAFANA_PORT}:${GRAFANA_PORT}'
