global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'docker_service_discovery'
    file_sd_configs:
      - files:
        - /prometheus-docker-sd/docker-targets.json
    relabel_configs:
      - action: labelmap
        regex: 'com_docker_compose_(.+)'
